# Generated by Django 6.0.2 on 2026-02-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_id",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Booking UID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("total_members", models.PositiveIntegerField(default=1)),
                (
                    "passport_photo",
                    models.ImageField(blank=True, null=True, upload_to="passports/"),
                ),
                ("additional_info", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tour Booking",
                "verbose_name_plural": "Tour Bookings",
            },
        ),
    ]
