# Generated by Django 6.0.2 on 2026-02-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_id",
            field=models.CharField(
                editable=False, max_length=50, unique=True, verbose_name="Booking UID"
            ),
        ),
    ]
