# Generated by Django 6.0.2 on 2026-02-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_booking_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="tour_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
