# Generated by Django 6.0.2 on 2026-02-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_tour_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Partial", "Partial"),
                    ("Paid", "Paid"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
