# Generated by Django 6.0.2 on 2026-02-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_payment_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={},
        ),
    ]
