# Generated by Django 6.0.2 on 2026-02-18 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_company_booking_company_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="company",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="company",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Company",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
